#!/bin/bash
#
# Modia VPS Initial Setup Script
#
# This script sets up a fresh VPS for running Modia:
# - Installs Node.js 20 LTS, PM2, Nginx
# - Creates application directories and user
# - Configures firewall
# - Sets up PostgreSQL via Docker
# - Configures Nginx site
#
# Usage: ./setup.sh [--domain example.com] [--ssl]
#
# Options:
#   --domain <domain>  Domain name for Nginx/SSL configuration
#   --ssl              Run certbot for Let's Encrypt SSL
#   --dry-run          Print what would be done without executing
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
DOMAIN=""
ENABLE_SSL=false
DRY_RUN=false
APP_USER="modia"
APP_DIR="/var/www/modia"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    --ssl)
      ENABLE_SSL=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      exit 1
      ;;
  esac
done

log() {
  echo -e "${GREEN}[SETUP]${NC} $1"
}

warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
  echo -e "${RED}[ERROR]${NC} $1"
  exit 1
}

run() {
  if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY-RUN]${NC} $*"
  else
    "$@"
  fi
}

# Check if running as root
if [ "$EUID" -ne 0 ] && [ "$DRY_RUN" = false ]; then
  error "Please run as root (sudo ./setup.sh)"
fi

log "Starting Modia VPS setup..."

# 1. Update system packages
log "Updating system packages..."
run apt-get update
run apt-get upgrade -y

# 2. Install essential packages
log "Installing essential packages..."
run apt-get install -y curl wget git ufw software-properties-common

# 3. Install Node.js 20 LTS via NodeSource
log "Installing Node.js 20 LTS..."
if ! command -v node &> /dev/null || [ "$(node -v | cut -d. -f1 | tr -d 'v')" -lt 20 ]; then
  run curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  run apt-get install -y nodejs
else
  log "Node.js $(node -v) already installed"
fi

# 4. Install PM2 globally
log "Installing PM2..."
run npm install -g pm2

# 5. Install Nginx
log "Installing Nginx..."
run apt-get install -y nginx

# 6. Install Docker and Docker Compose (for PostgreSQL)
log "Installing Docker..."
if ! command -v docker &> /dev/null; then
  run curl -fsSL https://get.docker.com | bash -
  run systemctl enable docker
  run systemctl start docker
else
  log "Docker already installed"
fi

# 7. Create application user (if not exists)
log "Creating application user: $APP_USER..."
if ! id "$APP_USER" &>/dev/null; then
  run useradd -m -s /bin/bash "$APP_USER"
  run usermod -aG docker "$APP_USER"
else
  log "User $APP_USER already exists"
fi

# 8. Create application directories
log "Creating application directories..."
run mkdir -p "$APP_DIR"/{releases,shared,backups/postgres}
run mkdir -p "$APP_DIR/shared/logs"
run chown -R "$APP_USER:$APP_USER" "$APP_DIR"

# 9. Configure firewall
log "Configuring firewall..."
run ufw allow ssh
run ufw allow http
run ufw allow https
run ufw --force enable

# 10. Create .env template
log "Creating .env template..."
if [ ! -f "$APP_DIR/shared/.env" ]; then
  cat > "$APP_DIR/shared/.env" << 'ENVEOF'
# Modia Production Environment
# Generated by setup.sh - UPDATE BEFORE DEPLOYING

NODE_ENV=production
PORT=3000

# Database (PostgreSQL)
DB_HOST=localhost
DB_PORT=5432
DB_NAME=modia_production
DB_USER=modia
DB_PASSWORD=CHANGE_THIS_PASSWORD

# JWT Secrets (generate with: openssl rand -base64 32)
JWT_SECRET=GENERATE_A_SECURE_SECRET
JWT_EXPIRES_IN=1h
JWT_REFRESH_SECRET=GENERATE_ANOTHER_SECURE_SECRET
JWT_REFRESH_EXPIRES_IN=7d

# World Generation
WORLD_SEED=123456

# CORS (update with your domain)
CORS_ORIGINS=https://your-domain.com

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000

# Trust proxy (1 = trust first hop, for nginx)
TRUST_PROXY=1

# Debug (set to false in production)
DEBUG=false
ENVEOF
  run chown "$APP_USER:$APP_USER" "$APP_DIR/shared/.env"
  warn "Created $APP_DIR/shared/.env - UPDATE WITH REAL VALUES BEFORE DEPLOYING"
else
  log ".env already exists, skipping"
fi

# 11. Create docker-compose for PostgreSQL
log "Creating PostgreSQL docker-compose..."
if [ ! -f "$APP_DIR/shared/docker-compose.yml" ]; then
  cat > "$APP_DIR/shared/docker-compose.yml" << 'DOCKEREOF'
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: modia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-modia_production}
      POSTGRES_USER: ${DB_USER:-modia}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-modia} -d ${DB_NAME:-modia_production}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
DOCKEREOF
  run chown "$APP_USER:$APP_USER" "$APP_DIR/shared/docker-compose.yml"
fi

# 12. Start PostgreSQL
log "Starting PostgreSQL..."
cd "$APP_DIR/shared"
if [ "$DRY_RUN" = false ]; then
  run sudo -u "$APP_USER" docker compose up -d
fi

# 13. Configure Nginx site
log "Configuring Nginx..."
NGINX_CONF="/etc/nginx/sites-available/modia"

if [ -n "$DOMAIN" ]; then
  SERVER_NAME="$DOMAIN www.$DOMAIN"
else
  SERVER_NAME="_"  # Default server
  warn "No domain specified, using default server name"
fi

cat > "$NGINX_CONF" << NGINXEOF
upstream modia_api {
    server 127.0.0.1:3000;
    keepalive 64;
}

server {
    listen 80;
    server_name $SERVER_NAME;

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Static files (Vite build output)
    root $APP_DIR/current/frontend/dist;
    index index.html;

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
    gzip_min_length 1000;

    # Static assets with caching
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # API proxy
    location /api/ {
        proxy_pass http://modia_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # WebSocket proxy
    location /ws {
        proxy_pass http://modia_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # SPA fallback
    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXEOF

# Enable site
run ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/modia
run rm -f /etc/nginx/sites-enabled/default

# Test and reload Nginx
run nginx -t
run systemctl reload nginx

# 14. SSL with Let's Encrypt (optional)
if [ "$ENABLE_SSL" = true ] && [ -n "$DOMAIN" ]; then
  log "Setting up Let's Encrypt SSL..."
  run apt-get install -y certbot python3-certbot-nginx
  run mkdir -p /var/www/certbot
  run certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN"

  # Setup SSL auto-renewal cron
  log "Setting up SSL auto-renewal..."
  if [ "$DRY_RUN" = false ]; then
    echo "0 0,12 * * * root certbot renew --quiet --deploy-hook 'systemctl reload nginx'" > /etc/cron.d/certbot-renewal
    chmod 644 /etc/cron.d/certbot-renewal
  else
    echo -e "${YELLOW}[DRY-RUN]${NC} Would create /etc/cron.d/certbot-renewal with renewal cron"
  fi
else
  if [ "$ENABLE_SSL" = true ]; then
    warn "SSL requested but no domain specified. Run with --domain to enable SSL."
  fi
fi

# 15. Setup PM2 startup
log "Configuring PM2 startup..."
if [ "$DRY_RUN" = false ]; then
  run pm2 startup systemd -u "$APP_USER" --hp "/home/$APP_USER"
fi

# 16. Summary
echo ""
log "========================================"
log "Modia VPS setup complete!"
log "========================================"
echo ""
echo "Next steps:"
echo "  1. Update $APP_DIR/shared/.env with real values"
echo "  2. Generate JWT secrets: openssl rand -base64 32"
echo "  3. Deploy the application: ./deploy.sh"
if [ -z "$DOMAIN" ]; then
  echo "  4. Update Nginx with your domain: --domain your-domain.com"
fi
if [ "$ENABLE_SSL" = false ]; then
  echo "  5. Enable SSL: certbot --nginx -d your-domain.com"
fi
echo ""
echo "Application directory: $APP_DIR"
echo "Application user: $APP_USER"
echo ""
