/**
 * Immutable V1 output digests captured before the version-dispatch refactor.
 *
 * These values are release fixtures, not snapshots generated by the test.
 * Hash input is the exact UTF-8 bytes of JSON.stringify(publicResult).
 */

export const V1_FIXTURE_DIGEST_ALGORITHM = 'sha256-json-stringify-v1';
export const V1_FIXTURE_SOURCE_COMMIT = '0cfa674a9b6c86bcf60effd800a127490ae106ce';

const productionOptions = Object.freeze({
  includeMetadata: true,
  includeSpawns: true,
  playerCount: 5,
  enemyAiType: 'aggressive',
  enemyCount: 5,
  enemyRoles: Object.freeze(['melee', 'ranged', 'support', 'tank', 'caster'])
});

const metadataOptions = Object.freeze({ includeMetadata: true });

const nodeVectors = [
  ['forest', 0, 'e89bb320cf85be0aabe303d63424831ac295e5ba385abc0c214ef22360e3dad6'],
  ['cave', 9973, '0d7806ba6c46cdd95c67085d47bdbe3f926ca30b49e01b5b81ad124d5d2589eb'],
  ['mountain', 19946, '5d368b229192808f60b94eca323fb056883c5cd12076c653b4a31b2542541219'],
  ['bridge', 29919, '6e9d66dee0117515c70031acdcd5117e068d4669c24cd1da599cef5b050e0403'],
  ['castle', 39892, '5c49782deb9d0b03631e26ddfa1c8978b0fd4b1ce035ed2d5afc5f86e3ecbd62'],
  ['dungeon', 49865, 'e74d5c466fca9434f72c2550d690a6b250bd2d65dc1119395a9d6c4296f92934'],
  ['swamp', 59838, '55b12d562114365903326ebb1befe4842a6f56b1a780873618b7ed66258e8f0f'],
  ['volcano', 69811, 'd272f64eaad00d0185573c292a70cbf46385482eb2d8c71f476922e456be26a3'],
  ['plains', 79784, 'dab9ac6703424cf23efe8603c8a13824710c5002dee257f56459e37fa19b7a1f'],
  ['arena', 89757, '2f3854ed29589d2019e57981fd3faddd4bdc32eeb2523125832b1c3ce81a83ed'],
  ['guild', 99730, 'e968cfb20da35e95cbb02e5ef76d7fdc0a5abd1906f197aa0932bb1afe934b72'],
  ['elven_grove', 109703, '4cb9b6c312629ad0cd46374a19a724883c712905afe1dd5143c389e09dc91dc9'],
  ['dwarven_mine', 119676, '20ec42984aa6560e0100b2b8a5ccd13ce8b9741ce6d8597ecd7797377445b12a'],
  ['vampiric_crypt', 129649, '4e6290a4c57b1e991ffb314008fea8d7a9d3a6570164ffecbe06fa1eebd3eca8'],
  ['orcish_warcamp', 139622, 'cd9a698c80b2a4255c4c1ebe280480681e7bc997db8d2bfe9f82aba3af776224'],
  ['human_ruins', 149595, '19823aa6356cd72ef855f21cf5b85f73deaf32497b0538aa138f4bd391dc35a5']
].map(([nodeType, seed, digest]) => Object.freeze({
  id: `node-${nodeType}`,
  seed,
  nodeType,
  width: 32,
  height: 32,
  options: productionOptions,
  digest
}));

const archetypeVectors = [
  ['openField', 'b6c52d3323b3521967093f8fa839ce94d5b9da45000d941d7aed84c237c102bf'],
  ['forestClearing', 'ce8fb7b535f5fa2e0a7a6e7d0713fd3fb970ddbbdaa8398dbdd6202229724bd0'],
  ['plains', '86dacc2760f23cdacf6b00712e644ca3439709ac41a73e9c2e4cd3f1925d2531'],
  ['caveRooms', 'c210f847774bb23ed65af60494d3185b19fd3a9341b193719dbb340904c47ff2'],
  ['tunnelNetwork', 'd5f891c30ecbb23cef797bb73dd0081f1d40513a1df462592da458e011d56b18'],
  ['crystalCavern', '828708ddc3ef5569b53c7f6465531fabaf9cf6cc15622cba73261370b3874aec'],
  ['dungeonHalls', '951399b741768ed9dc82d2cf64068aa71cc017a27b1d66917afd99b43987b14f'],
  ['crypt', 'cd85dc5a7b94ccb4115e0d89dfc735bcdc0d9bdb4055cf61b0f629de917a8e1f'],
  ['arena', '305e8733b59283afafa44ef24ed1ed178609df5834b0fa3bf471305045627906'],
  ['bridgeCrossing', '789e1873b21c1abc1baac3dff5dc8673c012f5701c16c2307e6291ff6ac587a8'],
  ['mountainPass', '2f24733695c3bb280154d32e113c76d1888817c8db39862fdb125e8e714fbec4'],
  ['ruinedCastle', '3869ea31d029d6dfce22b2328361867f655c6baf727f9a6c61199c9a4cff6a71'],
  ['swamp', 'f15cae4f720eddf3781bb76a2a8c634a82b7cd36e1a670dbfa213dca4b034271'],
  ['volcano', 'af00a3013af847842d63ea417292f8af2ad725e90f5765d8096d26ca9adb315b']
].map(([archetypeName, digest], index) => Object.freeze({
  id: `archetype-${archetypeName}`,
  seed: 24681357 + index,
  nodeType: 'forest',
  width: 32,
  height: 32,
  options: Object.freeze({ includeMetadata: true, archetypeName }),
  digest
}));

const sizeVectors = [
  ['size-minimum', -2147483648, 'forest', 10, 10, '3d49d80408af433c20da848894134332cbc2c1021de73aa40de441b9a67c42df'],
  ['size-arena-minimum', 2147483647, 'arena', 11, 16, '9168f1597c38716ec13c2c7c5cf313f1837f3f77b99ccba01145e8d919bc4fca'],
  ['size-nonsquare', -1, 'cave', 23, 17, 'd74906e07cbdda6d1e167206b151b4fdf084e4a87d15bfe2f9a1537535d86a31'],
  ['size-large-nonsquare', 4294967295, 'mountain', 48, 24, '2fb046961a916dd49f77e1f3be4bef6bdd9016d506847951d96679e71c00c2c7']
].map(([id, seed, nodeType, width, height, digest]) => Object.freeze({
  id,
  seed,
  nodeType,
  width,
  height,
  options: metadataOptions,
  digest
}));

export const V1_DIGEST_FIXTURES = Object.freeze([
  ...nodeVectors,
  ...archetypeVectors,
  ...sizeVectors
]);

